src/objects/Measurements__c.object
<CustomObject>
    <fields>
        <fullName>Direction__c</fullName>
        <label>Direction</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Front_Back__c</fullName>
        <label>Front Back</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Left_Right__c</fullName>
        <label>Left Right</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Wobble__c</fullName>
        <label>Wobble</label>
        <referenceTo>Wobble__c</referenceTo>
        <relationshipLabel>Measurements</relationshipLabel>
        <relationshipName>Measurements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Measurements</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Measurements Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Measurements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Wobble.cls
public class Wobble {

	@AuraEnabled
	public static Wobble__c createWobble(DateTime start, Decimal startMS){
		Wobble__c w = new Wobble__c(Start__c=start, Start_Milliseconds__c=startMS);
		insert w;
		return w;
	}

	@AuraEnabled
	public static Wobble__c finishWobble(String recId, DateTime stop, Decimal stopMS){
		Wobble__c w = new Wobble__c(Stop__c=stop, Id=recId, Stop_Milliseconds__c=stopMS);
		update w;
		return w;
	}

	@AuraEnabled
	public static Measurements__c recordMeasurements(Decimal lr, Decimal fb, Decimal dir, String wobId){
		Measurements__c meas = new Measurements__c(Left_Right__c = lr, Front_Back__c = fb, Direction__c = dir, Wobble__c = wobId);
		insert meas;
		return meas;
	}

}